export type DestinationDisposition =
  | "canonical"
  | "generated-shadow"
  | "structural-noop"
  | "unsupported";
export const DESTINATION_DISPOSITIONS = {
  bkmkend: "canonical",
  bkmkstart: "canonical",
  colortbl: "canonical",
  field: "canonical",
  fldinst: "canonical",
  fldrslt: "canonical",
  fonttbl: "canonical",
  footnote: "canonical",
  header: "canonical",
  headerl: "canonical",
  headerr: "canonical",
  headerf: "canonical",
  footer: "canonical",
  footerl: "canonical",
  footerr: "canonical",
  footerf: "canonical",
  hlink: "canonical",
  info: "canonical",
  listoverridetable: "canonical",
  listtable: "canonical",
  object: "canonical",
  objdata: "canonical",
  objclass: "canonical",
  pict: "canonical",
  pn: "canonical",
  shpinst: "canonical",
  stylesheet: "canonical",
  title: "canonical",
  subject: "canonical",
  author: "canonical",
  keywords: "canonical",
  lang: "canonical",
  doccomm: "canonical",
  category: "canonical",
  creatim: "structural-noop",
  comment: "structural-noop",
  levelnumbers: "canonical",
  leveltext: "canonical",
  listname: "canonical",
  list: "generated-shadow",
  nonshppict: "generated-shadow",
  pntext: "generated-shadow",
  pntxta: "generated-shadow",
  pntxtb: "generated-shadow",
  shppict: "generated-shadow",
  dbmajor: "generated-shadow",
  dbminor: "generated-shadow",
  fbimajor: "generated-shadow",
  fbiminor: "generated-shadow",
  expandedcolortbl: "generated-shadow",
  flomajor: "generated-shadow",
  flominor: "generated-shadow",
  fdbmajor: "generated-shadow",
  fdbminor: "generated-shadow",
  fhimajor: "generated-shadow",
  fhiminor: "generated-shadow",
  mmathPr: "generated-shadow",
  listlevel: "generated-shadow",
  nonesttables: "generated-shadow",
  upr: "generated-shadow",
  himajor: "generated-shadow",
  himinor: "generated-shadow",
  levelmarker: "generated-shadow",
  listtext: "generated-shadow",
  listoverride: "generated-shadow",
  pu: "generated-shadow",
  abinodiroverride: "structural-noop",
  dbch: "structural-noop",
  hich: "structural-noop",
  highlight: "structural-noop",
  htmlrtf: "structural-noop",
  ltrch: "structural-noop",
  loch: "structural-noop",
  rtlch: "structural-noop",
  version: "structural-noop",
  company: "unsupported",
  datafield: "unsupported",
  datastore: "unsupported",
  falttext: "unsupported",
  filetbl: "unsupported",
  manager: "unsupported",
  operator: "structural-noop",
  printim: "structural-noop",
  revtim: "structural-noop",
  vern: "structural-noop",
  proto: "unsupported",
  revtbl: "unsupported",
  rsidgrp: "unsupported",
  rsidtbl: "unsupported",
  themedata: "unsupported",
  xmlnstb: "unsupported",
} as const satisfies Record<string, DestinationDisposition>;

export const INLINE_NOOP_CONTROLS = new Set(["htmlrtf", "ltrch", "rtlch"]);
export const APP_METADATA_CONTROLS = new Set([
  "edmins",
  "nofchars",
  "nofcharsws",
  "nofpages",
  "nofwords",
]);
export function destinationDisposition(name: string): DestinationDisposition {
  return DESTINATION_DISPOSITIONS[name as keyof typeof DESTINATION_DISPOSITIONS] ?? "unsupported";
}
