import { Relationships } from "@office-open/core";
import { uniqueUuid } from "@office-open/core";

/**
 * Font Wrapper module for WordprocessingML documents.
 *
 * Manages font table relationships for embedded fonts.
 * Pure data container — no XmlComponent dependency.
 *
 * Reference: http://www.datypic.com/sc/ooxml/e-w_fonts.html
 *
 * @module
 */
import type { ViewWrapper } from "../../context";
import type { EmbeddedFontOptions } from "./font-table";

/**
 * Font options extended with a unique font key.
 */
export type EmbeddedFontOptionsWithKey = EmbeddedFontOptions & { fontKey: string };

/**
 * Wrapper class for managing embedded font relationships.
 *
 * Each font is assigned a unique key for obfuscation.
 * The actual font table XML is generated by `fontTableDesc.stringify()`.
 *
 * @example
 * ```typescript
 * const fontWrapper = new FontWrapper([
 *   { name: "CustomFont", data: fontBuffer }
 * ]);
 * ```
 */
export class FontWrapper implements ViewWrapper {
  public relationships: Relationships;
  public fontOptionsWithKey: EmbeddedFontOptionsWithKey[] = [];

  public constructor(public options: EmbeddedFontOptions[]) {
    this.fontOptionsWithKey = options.map((o) => ({ ...o, fontKey: uniqueUuid() }));
    this.relationships = new Relationships();

    for (let i = 0; i < options.length; i++) {
      this.relationships.addRelationship(
        i + 1,
        "http://schemas.openxmlformats.org/officeDocument/2006/relationships/font",
        `fonts/${options[i].name}.odttf`,
      );
    }
  }
}
