import { Relationships } from "@office-open/core";
import { uniqueUuid } from "@office-open/core";

/**
 * Font Wrapper module for WordprocessingML documents.
 *
 * Manages font table relationships for embedded fonts.
 * Pure data container — no XmlComponent dependency.
 *
 * Reference: http://www.datypic.com/sc/ooxml/e-w_fonts.html
 *
 * @module
 */
import type { ViewWrapper } from "../../context";
import type { EmbeddedFontOptions } from "./font-table";

/**
 * Font options extended with a unique font key.
 */
export type EmbeddedFontOptionsWithKey = EmbeddedFontOptions & {
  fontKey: string;
  /** Relationship id assigned to embedRegular (only fonts carrying data). */
  embedRid?: string;
};

/**
 * Wrapper class for managing embedded font relationships.
 *
 * Each embedded font is assigned a unique key for obfuscation.
 * The actual font table XML is generated by `fontTableDesc.stringify()`.
 *
 * @example
 * ```typescript
 * const fontWrapper = new FontWrapper([
 *   { name: "CustomFont", data: fontBuffer }
 * ]);
 * ```
 */
export class FontWrapper implements ViewWrapper {
  public relationships: Relationships;
  public fontOptionsWithKey: EmbeddedFontOptionsWithKey[] = [];

  public constructor(public options: EmbeddedFontOptions[]) {
    // Keep every font declaration — metadata-only fonts (no `data`) carry no
    // bytes to embed but must still round-trip into fontTable.xml. Only fonts
    // with binary data receive a fontKey + relationship for the .odttf part.
    this.fontOptionsWithKey = options.map(
      (o): EmbeddedFontOptionsWithKey => ({
        ...o,
        fontKey: o.data !== undefined ? (o.fontKey ?? uniqueUuid()) : (o.fontKey ?? ""),
      }),
    );
    this.relationships = new Relationships();

    let relIdx = 0;
    for (const font of this.fontOptionsWithKey) {
      if (font.data === undefined) continue;
      relIdx++;
      font.embedRid = `rId${relIdx}`;
      const target = font.odttfPath
        ? font.odttfPath.startsWith("word/")
          ? font.odttfPath.slice(5)
          : font.odttfPath
        : `fonts/${font.name}.odttf`;
      this.relationships.addRelationship(
        relIdx,
        "http://schemas.openxmlformats.org/officeDocument/2006/relationships/font",
        target,
      );
    }
  }
}
