import {
  encodeUriPath,
  RELATIONSHIP_TYPES,
  type ReproducibleScope,
  Relationships,
  toUint8Array,
  uniqueUuid,
} from "@office-open/core";
import type { Guid } from "@office-open/core";

/**
 * Font Wrapper module for WordprocessingML documents.
 *
 * Manages font table relationships for embedded fonts.
 * Pure data container — no XmlComponent dependency.
 *
 * Reference: http://www.datypic.com/sc/ooxml/e-w_fonts.html
 *
 * @module
 */
import type { ViewWrapper } from "../../context";
import type { EmbeddedFontOptions } from "./font-table";

/**
 * Font options extended with a unique font key.
 */
export type EmbeddedFontOptionsWithKey = EmbeddedFontOptions & {
  fontKey: Guid;
  /** Relationship id assigned to embedRegular (only fonts carrying data). */
  embedRid?: string;
  /** Normalized font bytes (Uint8Array regardless of the input form). */
  data?: Uint8Array;
};

/**
 * Wrapper class for managing embedded font relationships.
 *
 * Each embedded font is assigned a unique key for obfuscation.
 * The actual font table XML is generated by `fontTableDesc.stringify()`.
 *
 * @example
 * ```typescript
 * const fontWrapper = new FontWrapper([
 *   { name: "CustomFont", data: fontBuffer }
 * ]);
 * ```
 */
export class FontWrapper implements ViewWrapper {
  public relationships: Relationships;
  public fontOptionsWithKey: EmbeddedFontOptionsWithKey[] = [];

  public constructor(
    public options: EmbeddedFontOptions[],
    reproducible?: ReproducibleScope,
  ) {
    // Keep every font declaration — metadata-only fonts (no `data`) carry no
    // bytes to embed but must still round-trip into fontTable.xml. Only fonts
    // with binary data receive a fontKey + relationship for the .odttf part.
    this.fontOptionsWithKey = options.map((o): EmbeddedFontOptionsWithKey => ({
      ...o,
      data: o.data !== undefined ? toUint8Array(o.data) : undefined,
      fontKey:
        o.data !== undefined
          ? (o.fontKey ?? reproducible?.nextUuid() ?? uniqueUuid())
          : (o.fontKey ?? ""),
    }));
    this.relationships = new Relationships();

    let relIdx = 0;
    for (const font of this.fontOptionsWithKey) {
      if (font.data === undefined) continue;
      relIdx++;
      font.embedRid = `rId${relIdx}`;
      const target = font.odttfPath
        ? font.odttfPath.startsWith("word/")
          ? font.odttfPath.slice(5)
          : font.odttfPath
        : `fonts/${font.name}.odttf`;
      // A Target is a URI: escape the font part name per segment (spaces,
      // non-ASCII) so it matches the ZIP entry packed by compileDocument.
      this.relationships.addRelationship(relIdx, RELATIONSHIP_TYPES.font, encodeUriPath(target));
    }
  }
}
