export type {
  Attributes,
  DeclarationAttributes,
  Element,
  ElementCompact,
  IgnoreOptions,
  NonEmptyArray,
  ParseOptions,
  StringifyOptions,
} from "@office-open/xml";
export {
  allChildren,
  attr,
  attrBool,
  attrMeasure,
  attrNum,
  attrs,
  attrsRaw,
  childCount,
  children,
  childText,
  collectText,
  colorAttr,
  element,
  escapeXml,
  findChild,
  findDeep,
  findFirst,
  hasChild,
  isNonEmpty,
  nativeTypeValue,
  OOXML_XML_DECLARATION,
  parse,
  parseAttributes,
  selfCloseElement,
  stringify,
  stringifyElement,
  textOf,
  unescapeXml,
} from "@office-open/xml";
