export {
  createThemeXml,
  themeDesc,
  type ColorMappingOptions,
  type ColorSchemeOptions,
  type DefaultShapeDefinitionOptions,
  type EffectStyleOptions,
  type ExtraColorSchemeOptions,
  type FontCollectionOptions,
  type FontReferenceOptions,
  type FontSchemeOptions,
  type FormatSchemeOptions,
  type ObjectDefaultsOptions,
  type ShapeStyleOptions,
  type StyleMatrixReferenceOptions,
  type SupplementalFontOptions,
  type TextFontOptions,
  type ThemeOptions,
} from "@office-open/core/theme";
