import type { RunOptions } from "@office-open/docx";

import type { RunFormat } from "./models";

export const CONTENT_GROUP_CONTROLS = new Set([
  "b",
  "cell",
  "cellx",
  "cf",
  "bullet",
  "caps",
  "cgrid",
  "charscalex",
  "f",
  "emdash",
  "emspace",
  "endash",
  "fs",
  "enspace",
  "expnd",
  "expndtw",
  "i",
  "lang",
  "impr",
  "kerning",
  "line",
  "ldblquote",
  "lquote",
  "nestcell",
  "nestrow",
  "outl",
  "qmspace",
  "rdblquote",
  "rquote",
  "scaps",
  "shad",
  "cs",
  "nosupersub",
  "page",
  "par",
  "pard",
  "plain",
  "qc",
  "qj",
  "ql",
  "qr",
  "s",
  "strike",
  "sub",
  "super",
  "row",
  "sect",
  "tab",
  "trowd",
  "u",
  "uc",
  "ul",
  "ulnone",
  "ulw",
  "v",
]);

export function isFormatChanged(left: RunFormat, right: RunFormat): boolean {
  return (
    [
      "bold",
      "italic",
      "underline",
      "color",
      "size",
      "font",
      "strike",
      "verticalAlign",
      "language",
      "characterSpacing",
      "kern",
      "allCaps",
      "smallCaps",
      "outline",
      "shadow",
      "vanish",
      "emboss",
      "scale",
    ] as const
  ).some((key) => left[key] !== right[key]);
}

export function runOptions(format: RunFormat): RunOptions {
  return { ...format };
}
