/** Pivot XML child allowlist generated from sml.xsd; `*` allows extension payloads. */
export const PIVOT_ALLOWED_CHILDREN: Record<string, readonly string[]> = {
  ext: ["*"],
  autoFilter: ["extLst", "filterColumn", "sortState"],
  autoSortScope: ["pivotArea"],
  b: ["x"],
  cacheField: ["extLst", "fieldGroup", "mpMap", "sharedItems"],
  cacheFields: ["cacheField"],
  cacheHierarchies: ["cacheHierarchy"],
  cacheHierarchy: ["extLst", "fieldsUsage", "groupLevels"],
  cacheSource: ["consolidation", "extLst", "worksheetSource"],
  calculatedItem: ["extLst", "pivotArea"],
  calculatedItems: ["calculatedItem"],
  calculatedMember: ["extLst"],
  calculatedMembers: ["calculatedMember"],
  charset: [],
  chartFormat: ["pivotArea"],
  chartFormats: ["chartFormat"],
  colFields: ["field"],
  colHierarchiesUsage: ["colHierarchyUsage"],
  colHierarchyUsage: [],
  colItems: ["i"],
  color: [],
  colorFilter: [],
  condense: [],
  conditionalFormat: ["extLst", "pivotAreas"],
  conditionalFormats: ["conditionalFormat"],
  consolidation: ["pages", "rangeSets"],
  customFilter: [],
  customFilters: ["customFilter"],
  d: ["x"],
  dataField: ["extLst"],
  dataFields: ["dataField"],
  dateGroupItem: [],
  dimension: [],
  dimensions: ["dimension"],
  discretePr: ["x"],
  dynamicFilter: [],
  e: ["tpls", "x"],
  entries: ["e", "m", "n", "s"],
  extLst: ["*"],
  extend: [],
  family: [],
  field: [],
  fieldGroup: ["discretePr", "groupItems", "rangePr"],
  fieldUsage: [],
  fieldsUsage: ["fieldUsage"],
  filter: ["autoFilter", "extLst"],
  filterColumn: [
    "colorFilter",
    "customFilters",
    "dynamicFilter",
    "extLst",
    "filters",
    "iconFilter",
    "top10",
  ],
  filters: ["dateGroupItem", "filter"],
  format: ["extLst", "pivotArea"],
  formats: ["format"],
  group: ["groupMembers"],
  groupItems: ["b", "d", "e", "m", "n", "s"],
  groupLevel: ["extLst", "groups"],
  groupLevels: ["groupLevel"],
  groupMember: [],
  groupMembers: ["groupMember"],
  groups: ["group"],
  i: ["x"],
  iconFilter: [],
  item: [],
  items: ["item"],
  kpi: [],
  kpis: ["kpi"],
  location: [],
  m: ["tpls", "x"],
  map: [],
  maps: ["map"],
  measureGroup: [],
  measureGroups: ["measureGroup"],
  member: [],
  members: ["member"],
  mp: [],
  mpMap: [],
  mps: ["mp"],
  n: ["tpls", "x"],
  outline: [],
  page: ["pageItem"],
  pageField: ["extLst"],
  pageFields: ["pageField"],
  pageItem: [],
  pages: ["page"],
  pivotArea: ["extLst", "references"],
  pivotAreas: ["pivotArea"],
  pivotCacheDefinition: [
    "cacheFields",
    "cacheHierarchies",
    "cacheSource",
    "calculatedItems",
    "calculatedMembers",
    "dimensions",
    "extLst",
    "kpis",
    "maps",
    "measureGroups",
    "tupleCache",
  ],
  pivotCacheRecords: ["extLst", "r"],
  pivotField: ["autoSortScope", "extLst", "items"],
  pivotFields: ["pivotField"],
  pivotHierarchies: ["pivotHierarchy"],
  pivotHierarchy: ["extLst", "members", "mps"],
  pivotTableDefinition: [
    "chartFormats",
    "colFields",
    "colHierarchiesUsage",
    "colItems",
    "conditionalFormats",
    "dataFields",
    "extLst",
    "filters",
    "formats",
    "location",
    "pageFields",
    "pivotFields",
    "pivotHierarchies",
    "pivotTableStyleInfo",
    "rowFields",
    "rowHierarchiesUsage",
    "rowItems",
  ],
  pivotTableStyleInfo: [],
  query: ["tpls"],
  queryCache: ["query"],
  r: ["b", "d", "e", "m", "n", "rPr", "s", "t", "x"],
  rFont: [],
  rPr: [
    "b",
    "charset",
    "color",
    "condense",
    "extend",
    "family",
    "i",
    "outline",
    "rFont",
    "scheme",
    "shadow",
    "strike",
    "sz",
    "u",
    "vertAlign",
  ],
  rangePr: [],
  rangeSet: [],
  rangeSets: ["rangeSet"],
  reference: ["extLst", "x"],
  references: ["reference"],
  rowFields: ["field"],
  rowHierarchiesUsage: ["rowHierarchyUsage"],
  rowHierarchyUsage: [],
  rowItems: ["i"],
  s: ["tpls", "x"],
  scheme: [],
  serverFormat: [],
  serverFormats: ["serverFormat"],
  set: ["sortByTuple", "tpls"],
  sets: ["set"],
  shadow: [],
  sharedItems: ["b", "d", "e", "m", "n", "s"],
  sortByTuple: ["tpl"],
  sortCondition: [],
  sortState: ["extLst", "sortCondition"],
  strike: [],
  sz: [],
  t: ["n"],
  top10: [],
  tpl: [],
  tpls: ["tpl"],
  tupleCache: ["entries", "extLst", "queryCache", "serverFormats", "sets"],
  u: [],
  vertAlign: [],
  worksheetSource: [],
  x: [],
};
