/**
 * Post-generation gate for the AI tools: run the OPC package consistency check
 * on freshly generated bytes before handing them to the model.
 *
 * Fresh output is fully under library control, so ANY issue (error or warn) is
 * a library regression, not an options error — fail fast with the diagnosis
 * instead of shipping a file Word/Excel report as corrupt. Mirrors what
 * scripts/validate.ts runs in CI; O7-style duplicate relationship ids are
 * exactly the class of breakage this catches before a user sees it.
 *
 * @module
 */
import {
  encodeBase64,
  PART_REGISTRIES,
  unzipSync,
  validateOpcConsistency,
} from "@office-open/core";

import type { GenerateType } from "../generate";

// Binary parts (media, fonts) decode to replacement chars — the check only
// reads part presence and paths, never their content.
const decoder = new TextDecoder("utf-8", { fatal: false });

/** OPC-check a fresh package and return it as base64 for the tool result. */
export function generateVerifiedBase64(type: GenerateType, bytes: Uint8Array): string {
  const files = unzipSync(bytes);
  const entries = new Map<string, string>();
  for (const name of Object.keys(files)) {
    entries.set(name, decoder.decode(files[name]));
  }
  const issues = validateOpcConsistency(entries, PART_REGISTRIES[type]!);
  if (issues.length > 0) {
    const lines = issues.map((i) => `  ${i.code} [${i.severity}] ${i.part}: ${i.message}`);
    throw new Error(
      `Generated ${type} failed the OPC package consistency check — your options are valid, ` +
        `this is an office-open bug; please report it:\n${lines.join("\n")}`,
    );
  }
  return encodeBase64(bytes);
}
