/**
 * LibreOffice preset geometry names (ODF draw:type) mapped to ECMA ST_ShapeType
 * tokens. Sourced from LibreOffice core svx EnhancedCustomShapeTypeNames and
 * the ECMA preset token list; names without an OOXML counterpart (text boxes,
 * non-primitive geometry) are intentionally absent and fall back to no
 * geometry on conversion.
 *
 * @module
 */

import type { ShapeType } from "@office-open/core/drawing";

export const PRESET_GEOMETRY_DOCX: Record<string, ShapeType> = {
  "bent-arrow": "bentArrow",
  "bent-up-arrow": "bentUpArrow",
  "block-arc": "blockArc",
  "brace-pair": "bracePair",
  "bracket-pair": "bracketPair",
  can: "can",
  chevron: "chevron",
  circle: "ellipse",
  "circular-arrow": "circularArrow",
  cloud: "cloud",
  "cloud-callout": "cloudCallout",
  cross: "plus",
  cube: "cube",
  "curved-down-arrow": "curvedDownArrow",
  "curved-left-arrow": "curvedLeftArrow",
  "curved-right-arrow": "curvedRightArrow",
  "curved-up-arrow": "curvedUpArrow",
  diamond: "diamond",
  "diamond-callout": "wedgeRectCallout",
  "double-wave": "doubleWave",
  "down-arrow": "downArrow",
  "down-arrow-callout": "downArrowCallout",
  "eight-pointed-star": "star8",
  ellipse: "ellipse",
  "flowchart-alternate-process": "flowChartAlternateProcess",
  "flowchart-connector": "flowChartConnector",
  "flowchart-data": "flowChartInputOutput",
  "flowchart-decision": "flowChartDecision",
  "flowchart-delay": "flowChartDelay",
  "flowchart-direct-access-storage": "flowChartMagneticDisk",
  "flowchart-display": "flowChartDisplay",
  "flowchart-document": "flowChartDocument",
  "flowchart-internal-storage": "flowChartInternalStorage",
  "flowchart-manual-operation": "flowChartManualOperation",
  "flowchart-merge": "flowChartMerge",
  "flowchart-multidocument": "flowChartMultidocument",
  "flowchart-off-page-connector": "flowChartOffpageConnector",
  "flowchart-predefined-process": "flowChartPredefinedProcess",
  "flowchart-preparation": "flowChartPreparation",
  "flowchart-process": "flowChartProcess",
  "flowchart-summing-junction": "flowChartSummingJunction",
  "flowchart-terminator": "flowChartTerminator",
  "folded-corner": "foldedCorner",
  frame: "frame",
  funnel: "funnel",
  "half-frame": "snip2DiagRect",
  heart: "heart",
  hexagon: "hexagon",
  "horizontal-scroll": "horizontalScroll",
  "isosceles-triangle": "triangle",
  "left-arrow": "leftArrow",
  "left-arrow-callout": "leftArrowCallout",
  "left-brace": "leftBrace",
  "left-bracket": "leftBracket",
  "left-right-arrow": "leftRightArrow",
  "left-right-arrow-callout": "leftRightArrowCallout",
  lightning: "lightningBolt",
  megaphone: "wedgeEllipseCallout",
  moon: "moon",
  "notched-right-arrow": "notchedRightArrow",
  octagon: "octagon",
  parallelogram: "parallelogram",
  pentagon: "pentagon",
  "pentagon-right": "homePlate",
  "quad-arrow": "quadArrow",
  "quad-arrow-callout": "quadArrowCallout",
  rectangle: "rect",
  "rectangular-callout": "wedgeRectCallout",
  ribbon: "ribbon",
  "ribbon-2": "ribbon2",
  "right-arrow": "rightArrow",
  "right-arrow-callout": "rightArrowCallout",
  "right-brace": "rightBrace",
  "right-bracket": "rightBracket",
  "right-triangle": "rtTriangle",
  ring: "donut",
  "round-rectangle": "roundRect",
  "rounded-rectangular-callout": "wedgeRoundRectCallout",
  sheet: "plaque",
  "six-pointed-star": "star6",
  "sixteen-pointed-star": "star16",
  smiley: "smileyFace",
  "smiley-face": "smileyFace",
  star24: "star24",
  star4: "star4",
  star5: "star5",
  star8: "star8",
  "striped-right-arrow": "stripedRightArrow",
  sun: "sun",
  teardrop: "teardrop",
  "ten-pointed-star": "star10",
  "thirty-two-pointed-star": "star32",
  trapezoid: "trapezoid",
  "twelve-pointed-star": "star12",
  "twenty-four-pointed-star": "star24",
  "up-arrow": "upArrow",
  "up-arrow-callout": "upArrowCallout",
  "up-down-arrow": "upDownArrow",
  "up-down-arrow-callout": "upDownArrowCallout",
  "vertical-scroll": "verticalScroll",
  wave: "wave",
};

/** Reverse lookup: ST_ShapeType token → the first matching ODF preset name. */
export function presetGeometryOdf(token: ShapeType): string | undefined {
  for (const [odf, mapped] of Object.entries(PRESET_GEOMETRY_DOCX))
    if (mapped === token) return odf;
  return undefined;
}
