/**
 * Styles module for WordprocessingML documents.
 *
 * Pure collector — no XmlComponent inheritance.
 * Collects child elements as raw XML strings and serializes.
 *
 * Reference: http://officeopenxml.com/WPstyles.php
 *
 * @module
 */
import { attr, attrBool, attrNum, findChild } from "@office-open/xml";
import type { Element } from "@office-open/xml";
import { parseRunProperties } from "@parts/paragraph/run/run-parse";
import type {
  DefaultStylesOptions,
  BaseParagraphStyleOptions,
  BaseCharacterStyleOptions,
} from "@parts/styles/factory";
import { stringifyParagraphStyle, stringifyCharacterStyle } from "@parts/styles/factory";

/**
 * Options for configuring document styles.
 */
export interface StylesOptions {
  /** Default styles for document, headings, and common elements */
  default?: DefaultStylesOptions;
  /** Initial namespace attributes for the styles root element */
  initialAttributes?: Record<string, string>;
  /** Array of raw XML style elements */
  importedStyles?: { _raw: string }[];
  /** Array of custom paragraph style definitions */
  paragraphStyles?: (BaseParagraphStyleOptions & { id: string })[];
  /** Array of custom character style definitions */
  characterStyles?: (BaseCharacterStyleOptions & { id: string })[];
}

/**
 * Represents the styles definitions in a WordprocessingML document.
 *
 * Pure collector — no XmlComponent inheritance.
 * Collects child elements as raw XML strings and serializes.
 */
export class Styles {
  private attributes: Record<string, string> = {};
  private parts: string[] = [];

  public constructor(options: StylesOptions) {
    if (options.initialAttributes) {
      this.attributes = options.initialAttributes;
    }

    if (options.importedStyles) {
      for (const style of options.importedStyles) {
        if (style._raw) this.parts.push(style._raw);
      }
    }

    if (options.paragraphStyles) {
      for (const style of options.paragraphStyles) {
        this.parts.push(
          stringifyParagraphStyle({
            id: style.id,
            name: style.name ?? style.id,
            aliases: style.aliases,
            basedOn: style.basedOn,
            next: style.next,
            link: style.link,
            autoRedefine: style.autoRedefine,
            quickFormat: style.quickFormat,
            semiHidden: style.semiHidden,
            uiPriority: style.uiPriority,
            unhideWhenUsed: style.unhideWhenUsed,
            locked: style.locked,
            personal: style.personal,
            personalCompose: style.personalCompose,
            personalReply: style.personalReply,
            paragraph: style.paragraph,
            run: style.run,
          }),
        );
      }
    }

    if (options.characterStyles) {
      for (const style of options.characterStyles) {
        this.parts.push(
          stringifyCharacterStyle({
            id: style.id,
            name: style.name ?? style.id,
            aliases: style.aliases,
            basedOn: style.basedOn,
            link: style.link,
            autoRedefine: style.autoRedefine,
            semiHidden: style.semiHidden,
            uiPriority: style.uiPriority,
            unhideWhenUsed: style.unhideWhenUsed,
            locked: style.locked,
            personal: style.personal,
            personalCompose: style.personalCompose,
            personalReply: style.personalReply,
            run: style.run,
          }),
        );
      }
    }
  }

  /**
   * Serialize to word/styles.xml content (with XML declaration).
   */
  public serialize(): string {
    const attrParts: string[] = [];
    for (const [k, v] of Object.entries(this.attributes)) {
      if (v !== undefined && v !== null) attrParts.push(` ${k}="${v}"`);
    }

    const attrs = attrParts.join("");
    const body = this.parts.join("");
    return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:styles${attrs}>${body}</w:styles>`;
  }
}

// ── Parse helpers (for descriptor pipeline) ──

/** Style IDs generated by DefaultStylesFactory — skip these during parsing. */
const BUILTIN_STYLE_IDS = new Set([
  "Title",
  "Heading1",
  "Heading2",
  "Heading3",
  "Heading4",
  "Heading5",
  "Heading6",
  "Strong",
  "ListParagraph",
  "Hyperlink",
  "FootnoteText",
  "FootnoteTextChar",
  "EndnoteText",
  "EndnoteTextChar",
  "FootnoteReference",
  "EndnoteReference",
]);

/**
 * Build a cache of style elements keyed by styleId.
 */
export function buildStyleCache(stylesEl: Element | undefined): Map<string, Element> {
  const cache = new Map<string, Element>();
  if (!stylesEl) return cache;

  for (const child of stylesEl.elements ?? []) {
    if (child.name !== "w:style") continue;
    const styleId = attr(child, "w:styleId");
    if (styleId) {
      cache.set(styleId, child);
    }
  }

  return cache;
}

/**
 * Build a cache of abstract numbering elements keyed by abstractNumId.
 */
export function buildNumberingCache(numberingEl: Element | undefined): Map<string, Element> {
  const cache = new Map<string, Element>();
  if (!numberingEl) return cache;

  for (const child of numberingEl.elements ?? []) {
    if (child.name !== "w:abstractNum") continue;
    const abstractNumId = attr(child, "w:abstractNumId");
    if (abstractNumId !== undefined) {
      cache.set(abstractNumId, child);
    }
  }

  return cache;
}

/**
 * Parse w:styles element into StylesOptions-like structure.
 *
 * Skips built-in styles that DefaultStylesFactory already generates,
 * keeping only user-defined custom styles for round-trip fidelity.
 */
export function parseStyleDefinitions(
  el: Element,
  parseParagraphProperties: (el: Element, ctx: any) => Record<string, unknown>,
  ctx: any,
): Record<string, unknown> | undefined {
  const opts: Record<string, unknown> = {};
  const paragraphStyles: Record<string, unknown>[] = [];
  const characterStyles: Record<string, unknown>[] = [];

  for (const child of el.elements ?? []) {
    if (child.name === "w:docDefaults") {
      const defOpts = parseDocDefaults(child);
      if (defOpts) opts.default = defOpts;
    } else if (child.name === "w:style") {
      const styleOpts = parseStyleElement(child, parseParagraphProperties, ctx);
      if (!styleOpts) continue;

      const styleId = styleOpts.id as string | undefined;
      if (styleId && BUILTIN_STYLE_IDS.has(styleId)) continue;

      const type = styleOpts._type as string | undefined;
      delete styleOpts._type;

      if (type === "paragraph") {
        paragraphStyles.push(styleOpts);
      } else if (type === "character") {
        characterStyles.push(styleOpts);
      }
    }
  }

  if (paragraphStyles.length > 0) opts.paragraphStyles = paragraphStyles;
  if (characterStyles.length > 0) opts.characterStyles = characterStyles;

  return Object.keys(opts).length > 0 ? opts : undefined;
}

function parseDocDefaults(el: Element): Record<string, unknown> | undefined {
  const result: Record<string, unknown> = {};
  const docDefaults: Record<string, unknown> = {};

  const rPrDefault = findChild(el, "w:rPrDefault");
  if (rPrDefault) {
    const rPr = findChild(rPrDefault, "w:rPr");
    if (rPr) {
      const runDefaults = parseRunProperties(rPr);
      if (Object.keys(runDefaults).length > 0) docDefaults.run = runDefaults;
    }
  }

  const pPrDefault = findChild(el, "w:pPrDefault");
  if (pPrDefault) {
    const pPr = findChild(pPrDefault, "w:pPr");
    if (pPr) {
      const paraDefaults: Record<string, unknown> = {};
      const spacing = findChild(pPr, "w:spacing");
      if (spacing) {
        const sp: Record<string, unknown> = {};
        const before = attrNum(spacing, "w:before");
        if (before !== undefined) sp.before = before;
        const after = attrNum(spacing, "w:after");
        if (after !== undefined) sp.after = after;
        const line = attrNum(spacing, "w:line");
        if (line !== undefined) sp.line = line;
        if (Object.keys(sp).length > 0) paraDefaults.spacing = sp;
      }
      if (Object.keys(paraDefaults).length > 0) docDefaults.paragraph = paraDefaults;
    }
  }

  if (Object.keys(docDefaults).length > 0) result.document = docDefaults;
  return Object.keys(result).length > 0 ? result : undefined;
}

function parseStyleElement(
  el: Element,
  parseParagraphProperties: (el: Element, ctx: unknown) => Record<string, unknown>,
  ctx: unknown,
): (Record<string, unknown> & { _type?: string }) | undefined {
  const opts: Record<string, unknown> & { _type?: string } = {};

  const type = attr(el, "w:type");
  if (type) opts._type = type;

  const id = attr(el, "w:styleId");
  if (id) opts.id = id;

  const isDefault = attrBool(el, "w:default");
  if (isDefault) opts.default = true;

  const customStyle = attrBool(el, "w:customStyle");
  if (customStyle) opts.customStyle = "1";

  const nameEl = findChild(el, "w:name");
  if (nameEl) {
    const name = attr(nameEl, "w:val");
    if (name) opts.name = name;
  }

  const basedOn = findChild(el, "w:basedOn");
  if (basedOn) {
    const val = attr(basedOn, "w:val");
    if (val) opts.basedOn = val;
  }

  const next = findChild(el, "w:next");
  if (next) {
    const val = attr(next, "w:val");
    if (val) opts.next = val;
  }

  const link = findChild(el, "w:link");
  if (link) {
    const val = attr(link, "w:val");
    if (val) opts.link = val;
  }

  const uiPriority = findChild(el, "w:uiPriority");
  if (uiPriority) {
    const val = attrNum(uiPriority, "w:val");
    if (val !== undefined) opts.uiPriority = val;
  }

  if (findChild(el, "w:qFormat")) opts.quickFormat = true;
  if (findChild(el, "w:semiHidden")) opts.semiHidden = true;
  if (findChild(el, "w:unhideWhenUsed")) opts.unhideWhenUsed = true;
  if (findChild(el, "w:autoRedefine")) opts.autoRedefine = true;
  if (findChild(el, "w:locked")) opts.locked = true;
  if (findChild(el, "w:personal")) opts.personal = true;
  if (findChild(el, "w:personalCompose")) opts.personalCompose = true;
  if (findChild(el, "w:personalReply")) opts.personalReply = true;

  const aliases = findChild(el, "w:aliases");
  if (aliases) {
    const val = attr(aliases, "w:val");
    if (val) opts.aliases = val;
  }

  const pPr = findChild(el, "w:pPr");
  if (pPr) {
    const paraOpts = parseParagraphProperties(pPr, ctx);
    if (Object.keys(paraOpts).length > 0) opts.paragraph = paraOpts;
  }

  const rPr = findChild(el, "w:rPr");
  if (rPr) {
    const runOpts = parseRunProperties(rPr);
    if (Object.keys(runOpts).length > 0) opts.run = runOpts;
  }

  return opts;
}
