import type { UniversalMeasure } from "@office-open/core";
import type { NonVisualDrawingPropertiesOptions } from "@office-open/core/drawingml";
import type { TreeNode } from "@office-open/core/smartart";

export {
  getLayoutXml,
  getStyleXml,
  getColorXml,
  DEFAULT_DRAWING_XML,
  COLOR_CATEGORIES,
  LAYOUT_CATEGORIES,
  STYLE_CATEGORIES,
} from "@office-open/core/smartart";

export type { TreeNode };

/**
 * Options for a SmartArt diagram (p:graphicFrame).
 *
 * The single source of truth for both the public slide-child entry and the
 * descriptor — extends {@link NonVisualDrawingPropertiesOptions} so the
 * drawing's cNvPr (name/description/title/hidden) is authored uniformly with
 * every other drawing and survives a cross-format copy. `id`/`smartArtKey` are
 * auto-generated by the descriptor when omitted.
 *
 * @publicApi
 */
export interface SmartArtOptions extends NonVisualDrawingPropertiesOptions {
  /** Diagram id (p:cNvPr @id). Auto-generated if omitted. */
  id?: number;
  /** Pre-generated SmartArt key (e.g. "smartart_1024"). Auto-generated if omitted. */
  smartArtKey?: string;
  x?: number | UniversalMeasure;
  y?: number | UniversalMeasure;
  width?: number | UniversalMeasure;
  height?: number | UniversalMeasure;
  /** Tree-shaped data for the diagram content. */
  nodes: TreeNode[];
  /** Layout ID (e.g. "default", "process1", "hierarchy1") */
  layout?: string;
  /** Quick style ID (e.g. "simple1", "moderate1") */
  style?: string;
  /** Color transform ID (e.g. "accent1_2", "colorful1") */
  color?: string;
}
