import type { UniversalMeasure } from "@office-open/core";
import type { NonVisualDrawingPropertiesOptions } from "@office-open/core/drawing";
import type {
  ColorDefinitionOptions,
  LayoutDefinitionOptions,
  StyleDefinitionOptions,
  TreeNode,
} from "@office-open/core/smartart";

export {
  getLayoutXml,
  getStyleXml,
  getColorXml,
  DEFAULT_DRAWING_XML,
  COLOR_CATEGORIES,
  LAYOUT_CATEGORIES,
  STYLE_CATEGORIES,
} from "@office-open/core/smartart";

export type { TreeNode };

/**
 * Options for a SmartArt diagram (p:graphicFrame).
 *
 * The single source of truth for both the public slide-child entry and the
 * descriptor — extends {@link NonVisualDrawingPropertiesOptions} so the
 * drawing's cNvPr (name/description/title/hidden) is authored uniformly with
 * every other drawing and survives a cross-format copy. `id`/`smartArtKey` are
 * auto-generated by the descriptor when omitted.
 *
 * @publicApi
 */
export interface SmartArtOptions extends NonVisualDrawingPropertiesOptions {
  /** Diagram id (p:cNvPr `@id`). Auto-generated if omitted. */
  id?: number;
  /** Pre-generated SmartArt key (e.g. "smartart_1024"). Auto-generated if omitted. */
  smartArtKey?: string;
  x?: number | UniversalMeasure;
  y?: number | UniversalMeasure;
  width?: number | UniversalMeasure;
  height?: number | UniversalMeasure;
  /** Tree-shaped data for the diagram content. */
  nodes: TreeNode[];
  /** Built-in layout ID ("default", "process1") or a custom layout definition. */
  layout?: string | LayoutDefinitionOptions;
  /** Built-in quick style ID ("simple1") or a custom style definition. */
  style?: string | StyleDefinitionOptions;
  /** Built-in color transform ID ("accent1_2") or a custom color definition. */
  color?: string | ColorDefinitionOptions;
}
