name: Install dependencies and build ⚙️
description: Install dependencies and build

runs:
    using: composite
    steps:
        - name: Install Dependencies
          shell: bash
          run: pnpm install
        - name: Build
          shell: bash
          run: pnpm run build
