name: Validate
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/actions/install-and-build"
      - name: Validate Demos
        run: npx tsx scripts/validate.ts
